export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  APPLICATIONS: "/applications",
  POLICY_CREATE: "/policies/create",
  POLICY_DETAIL: (id: string) => `/policies/${id}`,
  CLAIM_CREATE: "/claims/create",
  CLAIM_DETAIL: (id: string) => `/claims/${id}`,
  CLAIM_TRACKING: "/claim-tracking",
  PAY_SCHEDULE: "/payments/schedule",
  PAY_LOGS: "/payments/logs",
  REPORTS: "/reports",
  PROFILE: "/profile",
  TERMS: "/terms",
  NOTIFICATIONS: "/notifications",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_CLAIMS: "/admin/claims",
  ADMIN_USERS: "/admin/users",
  ADMIN_AUDIT: "/admin/audit-logs",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_MAINTENANCE: "/admin/maintenance",
} as const;
